import Head from 'next/head'
import { prisma } from '../lib/prisma'
import { InferGetServerSidePropsType } from 'next'
import styles from '../styles/Home.module.css'
import AllArticles from '../component/AllArticles'

const Home = ({articles}:InferGetServerSidePropsType<typeof getServerSideProps>) => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{fontSize:"3.5rem"}}>Infinite Scroll Next JS</h1>
       <AllArticles articles={articles} />
      </main>

     
    </div>
  )
}

export default Home

export const getServerSideProps =async (context:any) => {
  const articles = await prisma.article.findMany({
    skip:0,
    take:3
  })
  return {
    props:{articles}
  }
}